"""Create source-scale comparisons and deterministic alpha QA for frozen outputs."""
from __future__ import annotations
import hashlib
import json
from pathlib import Path
from PIL import Image, ImageChops, ImageDraw, ImageStat
from tools.hd_ai.extract_samples import OUT
from tools.hd_ai.build_map_probe import water_mask


def main() -> None:
    samples=json.loads((OUT/'samples.json').read_text())['samples']
    out=OUT/'review';out.mkdir(exist_ok=True)
    records=[]
    for sample in samples:
        original=Image.open(OUT/sample['canvas']).convert('RGBA')
        rgb=Image.new('RGBA',original.size,(100,100,112,255));rgb.alpha_composite(original);rgb=rgb.convert('RGB')
        target=(original.width*4,original.height*4)
        baseline=original.resize(target,Image.Resampling.LANCZOS)
        baseline.save(out/f"{sample['id']}--lanczos.png")
        groups={1:[],2:[]}
        for f in sorted((OUT/'runs').glob(sample['id']+'--*/request.json')):
            req=json.loads(f.read_text())
            if req['status']!='completed':continue
            path=OUT/req['output'];raw=path.read_bytes()
            assert hashlib.sha256(raw).hexdigest()==req['output_sha256']
            generated=Image.open(path).convert('RGB')
            reduced=generated.resize(original.size,Image.Resampling.LANCZOS)
            mae=sum(ImageStat.Stat(ImageChops.difference(reduced,rgb)).mean)/3
            image=generated.resize(target,Image.Resampling.LANCZOS).convert('RGBA')
            alpha=original.getchannel('A').resize(target,Image.Resampling.LANCZOS)
            image.putalpha(alpha)
            assert not ImageChops.difference(image.getchannel('A'),baseline.getchannel('A')).getbbox()
            name=f"{sample['id']}--{req['model']}--{req['candidate']}--alpha.png"
            image.save(out/name)
            result={'sample':sample['id'],'model':req['model'],'candidate':req['candidate'],
                    'output_verified_sha256':True,'native_scale_rgb_mae':round(mae,4),
                    'alpha_difference_pixels_after_compositing':0,'composite':str((out/name).relative_to(OUT))}
            if sample['id']=='map-europe':
                a=water_mask(rgb);b=water_mask(reduced)
                intersection=sum(ImageChops.multiply(a,b).get_flattened_data())/255
                union=sum(ImageChops.lighter(a,b).get_flattened_data())/255
                result['water_mask_iou']=round(intersection/union,6)
            records.append(result)
            groups[req['candidate']].append((req['model'],image))
        for candidate,variants in groups.items():
            if not variants:continue
            columns=[('Original / nearest',original)]+variants
            sheet=Image.new('RGB',(len(columns)*320,360),'#20252c')
            for n,(label,image) in enumerate(columns):
                image=image.convert('RGBA');image.thumbnail((316,316),Image.Resampling.LANCZOS)
                if n==0:
                    scale=min(316/original.width,316/original.height)
                    image=original.resize((round(original.width*scale),round(original.height*scale)),Image.Resampling.NEAREST)
                else:
                    image=image.resize((316,round(316*image.height/image.width)),Image.Resampling.LANCZOS)
                bg=Image.new('RGBA',image.size,(100,100,112,255));bg.alpha_composite(image)
                sheet.paste(bg.convert('RGB'),(n*320+2,34+(316-image.height)//2))
                ImageDraw.Draw(sheet).text((n*320+4,10),label,fill='white')
            sheet.save(out/f"{sample['id']}--comparison-{candidate}.png")
    requests=[json.loads(f.read_text()) for f in (OUT/'runs').glob('*/request.json')]
    result={'schema':'srw64.hd-ai-output-review.v1','requests':len(requests),
        'completed_outputs':sum(r['status']=='completed' for r in requests),
        'reserved_cost_cny':round(sum(r['reserved_cny'] for r in requests),2),'cost_is_estimate':True,
        'actual_bill_verified':False,'records':records,
        'metric_limits':'MAE and water-mask IoU describe low-resolution drift, not aesthetic quality or ground-truth geometry.',
        'asia_sample_limit':'Source water is partly transparent, flattened on gray. The inherited deep-blue-water prompt is insufficiently specific; exclude from model-wide fidelity ranking.',
        'alpha_limits':'Alpha is deterministically restored from source, not generated by the models; boundary RGB still requires visual review.',
        'viapi':{'completed_outputs':0,'inference_requests':0,'upload_attempts':1,'upload_status':403,
                 'upload_error':'AccessDenied','service_entitlement':'not established',
                 'planned_outputs_not_executed':12,'temporary_credentials_saved':False}}
    (out/'qa.json').write_text(json.dumps(result,indent=2)+'\n')
    print(json.dumps({k:result[k] for k in ['requests','completed_outputs','reserved_cost_cny']}))


if __name__=='__main__': main()
