include_guard(GLOBAL)
# Shared by the real game build and the ROM/SDL-free GPU integration tests.
# Uses the same pinned DXC, SPIR-V->MSL converter and file_to_c as RT64.
function(srw64_add_pixel_compositor rt64_root)
    if(TARGET srw64_pixel_compositor)
        return()
    endif()
    get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
    set(source "${root}/src/native/presentation")
    set(output "${CMAKE_CURRENT_BINARY_DIR}/pixel-shaders")
    file(MAKE_DIRECTORY "${output}")
    add_library(srw64_pixel_compositor STATIC "${source}/pixel_compositor.cpp" "${source}/pixel_shaders.cpp")
    target_compile_features(srw64_pixel_compositor PUBLIC cxx_std_20)
    target_include_directories(srw64_pixel_compositor PUBLIC "${root}/src/native" "${rt64_root}/src/contrib/plume" PRIVATE "${output}")
    target_link_libraries(srw64_pixel_compositor PUBLIC plume)
    if(MSVC)
        target_compile_options(srw64_pixel_compositor PRIVATE /W4 /utf-8)
    else()
        target_compile_options(srw64_pixel_compositor PRIVATE -Wall -Wextra -Wpedantic)
    endif()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
        set(arch arm64)
    else()
        set(arch x64)
    endif()
    if(WIN32)
        set(dxc "${rt64_root}/src/contrib/dxc/bin/x64/dxc.exe")
    elseif(APPLE)
        set(dxc "${CMAKE_COMMAND}" -E env "DYLD_LIBRARY_PATH=${rt64_root}/src/contrib/dxc/lib/${arch}" "${rt64_root}/src/contrib/dxc/bin/${arch}/dxc-macos")
    else()
        set(dxc "${CMAKE_COMMAND}" -E env "LD_LIBRARY_PATH=${rt64_root}/src/contrib/dxc/lib/${arch}" "${rt64_root}/src/contrib/dxc/bin/${arch}/dxc-linux")
    endif()
    foreach(stage VS PS)
        if(stage STREQUAL "VS")
            set(profile vs_6_3)
            set(extra -fvk-invert-y)
        else()
            set(profile ps_6_3)
            set(extra)
        endif()
        set(shader "${source}/shaders/Pixel${stage}.hlsl")
        set(out "${output}/Pixel${stage}.hlsl")
        add_custom_command(OUTPUT "${out}.spv"
            COMMAND ${dxc} -spirv -fspv-target-env=vulkan1.0 -fvk-use-dx-layout ${extra} -E ${stage}Main -T ${profile} "${shader}" -Fo "${out}.spv"
            DEPENDS "${shader}" VERBATIM)
        if(APPLE)
            add_custom_command(OUTPUT "${out}.metal" COMMAND spirv_cross_msl "${out}.spv" "${out}.metal" DEPENDS "${out}.spv" spirv_cross_msl VERBATIM)
            if(SRW64_METAL_SOURCE_SHADERS)
                set(metal_input "${out}.metal")
            else()
                add_custom_command(OUTPUT "${out}.air" COMMAND xcrun -sdk macosx metal -c "${out}.metal" -o "${out}.air" DEPENDS "${out}.metal" VERBATIM)
                add_custom_command(OUTPUT "${out}.metallib" COMMAND xcrun -sdk macosx metallib "${out}.air" -o "${out}.metallib" DEPENDS "${out}.air" VERBATIM)
                set(metal_input "${out}.metallib")
            endif()
            add_custom_command(OUTPUT "${out}.metal.c" "${out}.metal.h"
                COMMAND file_to_c "${metal_input}" Pixel${stage}BlobMSL "${out}.metal.c" "${out}.metal.h"
                DEPENDS "${metal_input}" file_to_c VERBATIM)
            target_sources(srw64_pixel_compositor PRIVATE "${out}.metal.c")
        else()
            add_custom_command(OUTPUT "${out}.spirv.c" "${out}.spirv.h"
                COMMAND file_to_c "${out}.spv" Pixel${stage}BlobSPIRV "${out}.spirv.c" "${out}.spirv.h"
                DEPENDS "${out}.spv" file_to_c VERBATIM)
            target_sources(srw64_pixel_compositor PRIVATE "${out}.spirv.c")
            if(WIN32)
                add_custom_command(OUTPUT "${out}.dxil" COMMAND ${dxc} -E ${stage}Main -T ${profile} "${shader}" -Fo "${out}.dxil" DEPENDS "${shader}" VERBATIM)
                add_custom_command(OUTPUT "${out}.dxil.c" "${out}.dxil.h"
                    COMMAND file_to_c "${out}.dxil" Pixel${stage}BlobDXIL "${out}.dxil.c" "${out}.dxil.h"
                    DEPENDS "${out}.dxil" file_to_c VERBATIM)
                target_sources(srw64_pixel_compositor PRIVATE "${out}.dxil.c")
            endif()
        endif()
    endforeach()
endfunction()
