include_guard(GLOBAL)
# Optional CPU-only component. Deliberately does not change the game's default
# Core Text backend or add dependencies to existing lightweight contract tests.
function(srw64_add_portable_text)
    if(TARGET srw64_portable_text)
        return()
    endif()
    find_package(Freetype 2.10 REQUIRED)
    find_package(ICU 70 REQUIRED COMPONENTS uc i18n)
    find_package(harfbuzz CONFIG QUIET)
    if(NOT TARGET harfbuzz::harfbuzz)
        find_package(PkgConfig REQUIRED)
        pkg_check_modules(SRW64_HARFBUZZ REQUIRED IMPORTED_TARGET harfbuzz>=2.8)
        set(harfbuzz_target PkgConfig::SRW64_HARFBUZZ)
    else()
        set(harfbuzz_target harfbuzz::harfbuzz)
    endif()
    get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
    add_library(srw64_portable_text STATIC "${root}/src/native/text/portable_text.cpp")
    target_compile_features(srw64_portable_text PUBLIC cxx_std_20)
    target_include_directories(srw64_portable_text PUBLIC "${root}/src/native")
    target_link_libraries(srw64_portable_text PRIVATE
        Freetype::Freetype ${harfbuzz_target} ICU::uc ICU::i18n)
    if(MSVC)
        target_compile_options(srw64_portable_text PRIVATE /W4 /utf-8)
    else()
        target_compile_options(srw64_portable_text PRIVATE -Wall -Wextra -Wpedantic)
    endif()
endfunction()
